geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp
from django.views.generic import TemplateView

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name="login"),
    path('logout/', authapp.logout, name="logout"),
    path('register/', authapp.register, name="register"),
    path('update/', authapp.update, name='update'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
    path('send/mail/confirm/<str:message>', TemplateView.as_view(template_name='authapp/confirm.html'), name='send_confirm'),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('my/admin/', include('adminapp.urls', namespace='my_admin')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    path('auth/register/', include('social_django.urls', namespace='social')),

    path('admin/', admin.site.urls, name="admin"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name="index"),
    path('products/', mainapp.products, name="products"),
    path('products/<int:page>/', mainapp.products, name="same_products_pagination"),
    re_path(r'^category/(?P<pk>\d+)/products/$', mainapp.category_products, name="category_products"),
    # path(r'category/<int:pk>/products/', mainapp.category_products, name="category_products"),
    re_path(r'^category/(?P<pk>\d+)/products/(?P<page>\d+)/$', mainapp.category_products,
            name="category_products_pagination"),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product_page, name='product_page'),
    path('contacts/', cache_page(86400)(mainapp.contacts), name="contacts"),

    re_path(r'^product/detail/(?P<pk>\d+)/async/$', mainapp.product_detail_async),
]

geekshop/ordersapp/urls.py
from django.urls import path, re_path

import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='index'),
    path('order/create/', ordersapp.OrderCreate.as_view(), name='order_create'),
    path('order/update/<int:pk>/', ordersapp.OrderUpdate.as_view(), name='order_update'),
    path('order/delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
    path('order/read/<int:pk>/', ordersapp.OrderDetail.as_view(), name='order_read'),
    path('order/preparing/complete/<int:pk>/', ordersapp.order_preparing_complete, name='order_preparing_complete'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField('Название', max_length=128, unique=True)
    description = models.TextField('Описание', max_length=255, blank=True)
    is_active = models.BooleanField(default=True, db_index=True)
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)

    def __str__(self):
        return f'{self.name}'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.PROTECT, verbose_name='Категория')
    name = models.CharField('Название', max_length=128)
    short_description = models.CharField('Краткое описание', max_length=128, blank=True)
    description = models.TextField('Описание', blank=True)
    quantity = models.PositiveIntegerField('Количество', default=0)
    price = models.DecimalField('Цена', max_digits=10, decimal_places=0, default=0)
    image = models.ImageField(upload_to='products_images', blank=True)
    is_active = models.BooleanField(default=True, db_index=True)
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)
    updated_at = models.DateTimeField('Дата обновления', auto_now=True)

    @staticmethod
    def get_active_items():
        return Product.objects.select_related().filter(category__is_active=True, is_active=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

geekshop/mainapp/views.py
import random

from django.core.cache import cache
from django.views.decorators.cache import cache_page, never_cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
import json

from mainapp.models import ProductCategory, Product

from geekshop.settings import LOW_CACHE


def get_category_list():
    if LOW_CACHE:
        key = 'category_list'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if LOW_CACHE:
        key = f'productcategory_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_in_productcategory(pk):
    if LOW_CACHE:
        key = f'products_in_productcategory_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True)
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True,category__is_active=True)


def index(request):
    context = {
        'page_title': 'Interior',
    }
    return render(request, 'mainapp/index.html', context)


# @cache_page(3600)
# @never_cache
def products(request, page=1):
    # categories = ProductCategory.objects.all()
    # products_list = Product.objects.all()
    hot_product_pk = random.choice(Product.objects.filter(is_active=True).values_list('pk', flat=True))
    hot_product = get_product(hot_product_pk)
    same_products = hot_product.category.product_set.filter(is_active=True).select_related().exclude(pk=hot_product.pk)

    products_paginator = Paginator(same_products, 1)
    try:
        same_products = products_paginator.page(page)
    except PageNotAnInteger:
        same_products = products_paginator.page(1)
    except EmptyPage:
        same_products = products_paginator.page(products_paginator.num_pages)

    context = {
        'page_title': 'Products',
        'categories': get_category_list(),
        # 'products': products_list[:3],
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/product-details.html', context)


def category_products(request, pk, page=1):
    # categories = ProductCategory.objects.all()
    if pk == '0':
        category = {'pk': 0, 'name': 'Все'}
        products_list_category = get_products()
    else:
        category = get_category(pk)
        products_list_category = get_products_in_productcategory(pk)

    products_paginator = Paginator(products_list_category, 3)
    try:
        products_list_category = products_paginator.page(page)
    except PageNotAnInteger:
        products_list_category = products_paginator.page(1)
    except EmptyPage:
        products_list_category = products_paginator.page(products_paginator.num_pages)

    context = {
        'page_title': 'Products',
        'categories': get_category_list(),
        'products': products_list_category,
        'category': category,
    }
    return render(request, 'mainapp/category_products.html', context)


# @never_cache
def product_page(request, pk):
    # categories = ProductCategory.objects.all()
    product = get_product(pk)
    context = {
        'page_title': 'каталог',
        'categories': get_category_list(),
        'category': product.category,
        'product': product,
    }
    return render(request, 'mainapp/product.html', context)


# @cache_page(86400)
def contacts(request):
    with open('locations.json', 'r', encoding="utf-8") as file:
        locations = json.load(file)

    context = {
        'page_title': 'Contacts',
        'locations': locations,
    }

    return render(request, 'mainapp/contacts.html', context)


def product_detail_async(request, pk):
    if request.is_ajax():
        try:
            product = get_product(pk)
            return JsonResponse({
                'product_price': product.price,
            })
        except Exception as e:
            return JsonResponse({
                'error': str(e)
            })

geekshop/mainapp/templates/mainapp/includes/inc__categories_menu.html
<ul class="second-menu clearfix">
    <li class="second-menu-list">
        <a href="{% url 'main:category_products' 0 %}" class="second-menu-link
            {% if request.resolver_match.kwargs.pk == '0' %}
                second-menu-link-active
            {% endif %}">
            All
        </a>
    </li>
    {% for category in categories %}
        <li class="second-menu-list">
            <a href="{% url 'main:category_products' category.pk %}" class="second-menu-link
                {% if request.resolver_match.kwargs.pk|add:0 == category.pk %}
                    second-menu-link-active
                {% endif %}">
                {{ category.name }}
            </a>
        </li>
    {% endfor %}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc__main_menu.html
{% load static %}
<div class="header clearfix">
	<a href="{% url 'main:index' %}"><img src="{% static 'img/logo.svg' %}" alt="logo"></a>
	<ul class="menu clearfix">
		<li class="menu-list">
			<a href="{% url 'main:index' %}" class="menu-link {% if request.resolver_match.view_name == 'main:index' %}
                        menu-link-active
                      {% endif %}">HOME</a>
		</li>
		<li class="menu-list">
			<a href="{% url 'main:products' %}" class="menu-link {% if request.resolver_match.view_name == 'main:products' %}
                        menu-link-active
                      {% endif %}">PRODUCTS</a>
		</li>
<!--	<li class="menu-list"><a href="#" class="menu-link">HISTORY</a></li>-->
<!--	<li class="menu-list"><a href="#" class="menu-link">SHOWROOM</a></li>-->
		<li class="menu-list">
			<a href="{% url 'main:contacts' %}" class="menu-link {% if request.resolver_match.view_name == 'main:contacts' %}
                        menu-link-active
                      {% endif %}">CONTACT</a>
		</li>
		{% if user.is_authenticated %}
			<li class="menu-list">
				<div class="dropdown">
					<a class="dropdown-toggle menu-link" href="" data-toggle="dropdown">
						{{ user.first_name|default:'пользователь'|title }}
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li>
							<a href="{% url 'auth:update' %}" class="menu-link">
								профиль
							</a>
						</li>
						<li>
							<a href="{% url 'ordersapp:index' %}" class="menu-link">
								заказы
							</a>
						</li>
					</ul>
				</div>
            </li>
        {% endif %}
		{% if user.is_superuser %}
            <li class="menu-list">
                <a href="{% url 'my_admin:index' %}" class="menu-link">
                    Админка
                </a>
            </li>
        {% endif %}
        <li class="menu-list">
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}" class="menu-link">
                    выход
                </a>
            {% else %}
                <a href="{% url 'auth:login' %}" class="menu-link">
                    вход
                </a>
            {% endif %}
			{% csrf_token %}
        </li>
		<li class="menu-list">
			<a href="#" class="menu-link">
				<img src="{% static 'icons/search.svg' %}" alt="search">
			</a>
		</li>
	</ul>
</div>
<div class="basket">
	<a href="{% url 'basket:index' %}" class="menu-link">
		<span>Корзина:</span><br>
		<span>
			{% if basket %}
				{{ basket.0.total_cost|floatformat:0 }} руб ({{ basket.0.total_quantity }} шт)
			{% endif %}
		</span>
	</a>
</div>