geekshop/adminapp/urls.py
from django.urls import path, re_path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.ShopUserList.as_view(), name='index'),
    path('user/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('user/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('user/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('category/list/', adminapp.CategoriesListView.as_view(), name='categories'),
    path('category/list/<int:page>/', adminapp.CategoriesListView.as_view(), name="categories_pagination"),
    path('category/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    re_path(r'^category/(?P<pk>\d+)/products_list/$', adminapp.CategoryProductsListView.as_view(),
            name='category_products_list'),
    path('category/<int:pk>/products_list/<int:page>/', adminapp.CategoryProductsListView.as_view(),
         name="category_products_list_pagination"),

    # TODO: сделать проброс category_id
    path('category/product/create/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('product/read/<int:pk>/', adminapp.ProductDetail.as_view(), name='product_read'),

    path('product/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),

    # path('', adminapp.index, name='index'),
    # path('user/create/', adminapp.user_create, name='user_create'),
    # path('user/update/<int:pk>/', adminapp.user_update, name='user_update'),
    # path('user/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    # path('category/list/', adminapp.categories, name='categories'),
    # path('category/list/<int:page>/', adminapp.categories, name="categories_pagination"),
    # path('category/create/', adminapp.category_create, name='category_create'),
    # path('category/update/<int:pk>/', adminapp.category_update, name='category_update'),
    # path('category/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),
    # path('category/<int:pk>/products_list/', adminapp.category_products_list, name='category_products_list'),
    # path('category/<int:pk>/products_list/<int:page>/', adminapp.category_products_list,
    #      name="category_products_list_pagination"),
    # path('category/<int:category_pk>/product/create/', adminapp.product_create, name='product_create'),
    # path('product/read/<int:pk>/', adminapp.product_read, name='product_read'),
    # path('product/update/<int:pk>/', adminapp.product_update, name='product_update'),
    # path('product/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp
from django.views.generic import TemplateView

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name="login"),
    path('logout/', authapp.logout, name="logout"),
    path('register/', authapp.register, name="register"),
    path('update/', authapp.update, name='update'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
    path('send/mail/confirm/<str:message>', TemplateView.as_view(template_name='authapp/confirm.html'), name='send_confirm'),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('my/admin/', include('adminapp.urls', namespace='my_admin')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    path('auth/register/', include('social_django.urls', namespace='social')),

    path('admin/', admin.site.urls, name="admin"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from authapp.forms import forms
from authapp.models import ShopUser
from mainapp.models import ProductCategory
from mainapp.models import Product


class AdminShopUserCreateForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = (
            'username', 'first_name', 'last_name', 'is_superuser',
            'password1', 'password2', 'email', 'age', 'avatar'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Пользователь слишком молод!")
        return data


class AdminShopUserUpdateForm(UserChangeForm):
    class Meta:
        model = ShopUser
        # fields = '__all__'
        fields = (
            'username', 'first_name', 'last_name', 'is_superuser',
            'password', 'email', 'age', 'avatar', 'is_active', 'is_staff'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'password':
                field.widget = forms.HiddenInput()
            else:
                field.widget.attrs['class'] = 'form-control'
                field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Пользователь слишком молод!")
        return data


class AdminProductCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class AdminProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

geekshop/adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from authapp.models import ShopUser
from mainapp.models import Product
from mainapp.models import ProductCategory
from adminapp.forms import AdminShopUserCreateForm
from adminapp.forms import AdminShopUserUpdateForm
from adminapp.forms import AdminProductCategoryUpdateForm
from adminapp.forms import AdminProductUpdateForm


class SuperUserOnlyMixin:
    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class PageTitleMixin:
    page_title = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.page_title
        return context


class ShopUserList(SuperUserOnlyMixin, PageTitleMixin, ListView):
    model = ShopUser
    page_title = 'Админка'


class UserCreateView(SuperUserOnlyMixin, PageTitleMixin, CreateView):
    model = ShopUser
    success_url = reverse_lazy('my_admin:index')
    form_class = AdminShopUserCreateForm
    page_title = 'Создать пользователя'


class UserUpdateView(SuperUserOnlyMixin, PageTitleMixin, UpdateView):
    model = ShopUser
    success_url = reverse_lazy('my_admin:index')
    form_class = AdminShopUserUpdateForm
    page_title = 'Редактирование пользователя'


class UserDeleteView(SuperUserOnlyMixin, DeleteView):
    model = ShopUser
    success_url = reverse_lazy('my_admin:index')
    page_title = 'Удаление пользователя'    # TODO: проверить почему не работает

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class CategoriesListView(SuperUserOnlyMixin, PageTitleMixin, ListView):
    model = ProductCategory
    page_title = 'Админка/категории'
    paginate_by = 2


class CategoryCreateView(SuperUserOnlyMixin, PageTitleMixin, CreateView):
    model = ProductCategory
    success_url = reverse_lazy('my_admin:categories')
    form_class = AdminProductCategoryUpdateForm
    page_title = 'Категории продуктов/Создание'


class CategoryUpdateView(SuperUserOnlyMixin, PageTitleMixin, UpdateView):
    model = ProductCategory
    success_url = reverse_lazy('my_admin:categories')
    form_class = AdminProductCategoryUpdateForm
    page_title = 'Категории продуктов/Редактирование'


class CategoryDeleteView(SuperUserOnlyMixin, DeleteView):
    model = ProductCategory
    success_url = reverse_lazy('my_admin:categories')
    page_title = 'Категории продуктов/Удаление'    # TODO: проверить почему не работает

    # TODO: сделать удаление/скрытие каскадом, чтобы товары этой категории также были скрыты при ее удалении
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class CategoryProductsListView(SuperUserOnlyMixin, PageTitleMixin, ListView):
    model = Product
    # category = model.objects.all()[0].category
    # page_title = f'категория {category.name}/продукты'    # TODO: сделать получение имени категории
    paginate_by = 2
    # TODO: сделать проброс category_id
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['category_id'] = Product.objects.get(category_id=pk)
    #     return context


# TODO: сделать проброс category_id
class ProductCreateView(SuperUserOnlyMixin, PageTitleMixin, CreateView):
    model = Product
    success_url = reverse_lazy('my_admin:categories')
    form_class = AdminProductUpdateForm
    page_title = 'Создание продукта'


class ProductUpdateView(SuperUserOnlyMixin, PageTitleMixin, UpdateView):
    model = Product
    success_url = reverse_lazy('my_admin:categories')
    form_class = AdminProductUpdateForm
    page_title = 'Продукты/редактирование'


class ProductDeleteView(SuperUserOnlyMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('my_admin:categories')
    page_title = 'Продукты/Удаление'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class ProductDetail(DetailView):
    model = Product
    pk_url_kwarg = 'pk'     # product_pk


# @user_passes_test(lambda x: x.is_superuser)
# def index(request):
#     users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#     context = {
#         'title': 'Админка',
#         'object_list': users_list
#     }
#     return render(request, 'adminapp/index.html', context)


# @user_passes_test(lambda x: x.is_superuser)
# def user_create(request):
#     if request.method == 'POST':
#         user_form = AdminShopUserCreateForm(request.POST, request.FILES)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('my_admin:index'))
#     else:
#         user_form = AdminShopUserCreateForm()
#
#     context = {
#         'title': 'Создать пользователя',
#         'form': user_form
#     }
#
#     return render(request, 'adminapp/user_update.html', context)


# @user_passes_test(lambda x: x.is_superuser)
# def user_update(request, pk):
#     user = get_object_or_404(ShopUser, pk=pk)
#     if request.method == 'POST':
#         user_form = AdminShopUserUpdateForm(request.POST, request.FILES, instance=user)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('my_admin:index'))
#     else:
#         user_form = AdminShopUserUpdateForm(instance=user)
#
#     context = {
#         'title': 'Редактирование пользователя',
#         'form': user_form,
#     }
#
#     return render(request, 'adminapp/user_update.html', context)


# @user_passes_test(lambda x: x.is_superuser)
# def user_delete(request, pk):
#     user = get_object_or_404(ShopUser, pk=pk)
#     if request.method == 'POST':
#         user.is_active = False
#         user.save()
#         return HttpResponseRedirect(reverse('my_admin:index'))
#
#     context = {
#         'title': 'Удаление пользователя',
#         'user_to_delete': user,
#     }
#
#     return render(request, 'adminapp/user_delete.html', context)


# @user_passes_test(lambda x: x.is_superuser)
# def categories(request, page=1):
#     categories = ProductCategory.objects.all()
#
#     products_paginator = Paginator(categories, 2)
#     try:
#         categories = products_paginator.page(page)
#     except PageNotAnInteger:
#         categories = products_paginator.page(1)
#     except EmptyPage:
#         categories = products_paginator.page(products_paginator.num_pages)
#
#     context = {
#         'title': 'Админка/категории',
#         'object_list': categories,
#     }
#     return render(request, 'adminapp/productcategory_list.html', context)


# @user_passes_test(lambda x: x.is_superuser)
# def category_create(request):
#     if request.method == 'POST':
#         form = AdminProductCategoryUpdateForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('my_admin:categories'))
#     else:
#         form = AdminProductCategoryUpdateForm()
#
#     context = {
#         'title': 'Категории продуктов/Создание',
#         'form': form,
#     }
#
#     return render(request, 'adminapp/category_update.html', context)


# @user_passes_test(lambda x: x.is_superuser)
# def category_update(request, pk):
#     obj = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         form = AdminProductCategoryUpdateForm(request.POST, request.FILES, instance=obj)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('my_admin:categories'))
#     else:
#         form = AdminProductCategoryUpdateForm(instance=obj)
#
#     context = {
#         'title': 'Категории продуктов/Редактирование',
#         'form': form,
#     }
#
#     return render(request, 'adminapp/category_update.html', context)


# @user_passes_test(lambda x: x.is_superuser)
# def category_delete(request, pk):
#     obj = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         obj.is_active = False
#         obj.save()
#         return HttpResponseRedirect(reverse('my_admin:categories'))
#
#     context = {
#         'title': 'Категории продуктов/Удаление',
#         'object': obj,
#     }
#
#     return render(request, 'adminapp/category_delete.html', context)


# @user_passes_test(lambda x: x.is_superuser)
# def category_products_list(request, pk, page=1):
#     category = get_object_or_404(ProductCategory, pk=pk)
#     object_list = category.product_set.all()
#
#     products_paginator = Paginator(object_list, 2)
#     try:
#         object_list = products_paginator.page(page)
#     except PageNotAnInteger:
#         object_list = products_paginator.page(1)
#     except EmptyPage:
#         object_list = products_paginator.page(products_paginator.num_pages)
#
#     context = {
#         'title': f'категория {category.name}/продукты',
#         'category': category,
#         'object_list': object_list
#     }
#     return render(request, 'adminapp/category_products_list.html', context)

# @user_passes_test(lambda u: u.is_superuser)
# def product_create(request, category_pk):

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|capfirst }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="admin_container">
    <div class="h2 text-center head">
        Админка
    </div>
    {% block menu %}
        <div class="admin_menu">
            {% include 'adminapp/includes/inc__menu.html' %}
        </div>
    {% endblock %}

    {% block container %}
    {% endblock %}

</div>
</body>
</html>

geekshop/adminapp/templates/adminapp/categories_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block container %}
    <div class="categories_list">
        <a href="{% url 'my_admin:category_create' %}"
           class="btn btn-primary new_category">
            новая категория
        </a>
        {% for object in object_list %}
            <div class="category_record {% if not object.is_active %}not_active{% endif %}">
                <div class="category_name">
                    {{ object.name|title }}
                </div>
                <div class="category_actions">
                    <a href="{% url 'my_admin:category_products_list' object.pk %}"
                       class="btn btn-info">
                        товары категории
                    </a>
                    <a href="{% url 'my_admin:category_update' object.pk %}"
                       class="btn btn-success">
                        редактировать
                    </a>
                    <a href="{% url 'my_admin:category_delete' object.pk %}"
                       class="btn btn-danger">
                        удалить
                    </a>
                </div>
                <div class="category_desc">
                    {{ object.description }}
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="paginator">
            {% if object_list.has_previous %}
                <a href="{% url 'my_admin:categories_pagination' 1 %}">
                    <<
                </a>
                <a href="{% url 'my_admin:categories_pagination' object_list.previous_page_number %}">
                    <
                </a>
            {% endif %}
            <span class="current">страница {{ object_list.number }} из {{ object_list.paginator.num_pages }}</span>
            {% if object_list.has_next %}
                <a href="{% url 'my_admin:categories_pagination' object_list.next_page_number %}">
                    >
                </a>
                <a href="{% url 'my_admin:categories_pagination' object_list.paginator.num_pages %}">
                    >>
                </a>
            {% endif %}
        </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="user_delete">
        Уверены, что хотите удалить категорию <b>{{ object.name }}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <a href="{% url 'my_admin:categories' %}"
           class="btn btn-success">
            отмена
        </a>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_products_list.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_filters %}


{% block container %}
    <div class="products_list">
        <a class="new_product btn btn-default"
           href="{% url 'my_admin:product_create' category.pk %}">новый продукт</a>

        {% for object in object_list %}
            <div class="product_record {% if not object.is_active %}not_active{% endif %}">
                <img src="{{ object.image|media_folder_products }}" alt="{{ object.name }}">
                <div class="product_name">
                    {{ object.name|title }}
                </div>
                <div class="product_actions">
                    <button>
                        <a href="{% url 'my_admin:product_read' object.pk %}">подробнее</a>
                    </button>
                    <button>
                        <a href="{% url 'my_admin:product_update' object.pk %}">редактировать</a>
                    </button>
                    <button>
                        <a href="{% url 'my_admin:product_delete' object.pk %}">удалить</a>
                    </button>
                </div>
                <div class="summary">
                    <b>цена</b>
                    <p>{{ object.price }} руб</p>
                    <b>количество</b>
                    <p>{{ object.quantity }}</p>
                </div>
                <div class="product_desc">
                    {{ object.short_desc|capfirst }}
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="paginator">
            {% if object_list.has_previous %}
                <a href="{% url 'my_admin:category_products_list_pagination' category.pk 1 %}">
                    <<
                </a>
                <a href="{% url 'my_admin:category_products_list_pagination' category.pk object_list.previous_page_number %}">
                    <
                </a>
            {% endif %}
            <span class="current">страница {{ object_list.number }} из {{ object_list.paginator.num_pages }}</span>
            {% if object_list.has_next %}
                <a href="{% url 'my_admin:category_products_list_pagination' category.pk object_list.next_page_number %}">
                    >
                </a>
                <a href="{% url 'my_admin:category_products_list_pagination' category.pk object_list.paginator.num_pages %}">
                    >>
                </a>
            {% endif %}
        </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'my_admin:categories' %}"
           class="btn btn-primary form-control last">
            к списку категорий
        </a>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/index.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_filters %}

{% block container %}
    <div class="users_list">
        <a href="{% url 'my_admin:user_create' %}" class="btn btn-primary new_user">
            новый пользователь
        </a>
        {% for shop_user in object_list %}
            <div class="user_record {% if not shop_user.is_active %}not_active{% endif %}">
                <img src="{{ shop_user.avatar|media_folder_users }}" alt="{{ shop_user.username }}">
                <div class="user_role">
                    {% if shop_user.is_superuser %}администратор{% else %}пользователь{% endif %}
                    <a href="{% url 'my_admin:user_update' shop_user.pk %}" class="btn btn-primary">
                        редактировать
                    </a>
                    <a href="{% url 'my_admin:user_delete' shop_user.pk %}" class="btn btn-danger">
                        удалить
                    </a>
                </div>
                <div class="user_name">
                    <p><strong>{{ shop_user.username }}</strong></p>
                    <p>
                        {% if shop_user.first_name %}
                            <b>{{ shop_user.first_name|title }}</b>
                            {% if shop_user.last_name %}
                                <p>{{ shop_user.last_name|title }}</p>
                            {% endif %}
                        {% endif %}
                    </p>
                </div>
                <div class="user_age">
                    age:<br>
                    {{ shop_user.age }} лет
                </div>
                <div class="user_email">
                    email:<br>
                    {{ shop_user.email }}
                </div>
                <div class="user_lastlogin">
                    logged:<br>
                    {{ shop_user.last_login }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="user_delete">
        Уверены, что хотите удалить продукт <b>{{ object.name }}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <a href="{% url 'my_admin:category_products_list' object.category.pk %}"
           class="btn btn-success">
            отмена
        </a>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="product_read">
        <div class="produt_name">
            Продукт<strong>{{ object.category.name|title }} /
            {{ object.name|title }}</strong>
        </div>
        <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <a href="{% url 'my_admin:product_update' object.pk %}" class="btn btn-primary">
                    редактировать
                </a>
            </p>
            <p>
                <a href="{% url 'my_admin:product_delete' object.pk %}" class="btn btn-danger">
                    удалить
                </a>
            </p>
            <p>
                <a href="{% url 'my_admin:product_update' object.category.pk %}" class="btn btn-default">
                    назад
                </a>
            </p>
        </div>
        <div class="product_desc">
            <b>Краткая информация</b>
            <p>{{ object.short_description }}</p>
            <br><br>
            <b>Подробная информация</b>
            <p>{{ object.description }}</p>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'my_admin:category_products_list' category.pk %}"
           class="btn btn-primary form-control last">
            к списку продуктов
        </a>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="user_delete">
        Уверены, что хотите удалить <b>{{ user_to_delete.username }}
        {% if user_to_delete.first_name %}
            ({{ user_to_delete.first_name|title }}
                {% if user_to_delete.last_name %}
                    {{ user_to_delete.last_name|title }}
                {% endif %})
        {% endif %}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <a href="{% url 'my_admin:index' %}" class="btn btn-success">
            отмена
        </a>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'my_admin:index' %}"
           class="btn btn-primary form-control last">
            к списку пользователей
        </a>
    </div>
{% endblock %}