geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp
from django.views.generic import TemplateView

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name="login"),
    path('logout/', authapp.logout, name="logout"),
    path('register/', authapp.register, name="register"),
    path('update/', authapp.update, name='update'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
    path('send/mail/confirm/<str:message>', TemplateView.as_view(template_name='authapp/confirm.html'), name='send_confirm'),
]

geekshop/basketapp/urls.py
from django.urls import path, re_path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('<int:page>/', basketapp.index, name='index_pagination'),
    re_path(r'add/product/(?P<pk>\d+)/', basketapp.add_product, name="add_product"),
    # path('add/product/<int:pk>'/, basketapp.add_product, name="add_product"),
    re_path(r'delete/product/(?P<pk>\d+)/', basketapp.delete_product, name="delete_product"),
    re_path(r'^change/(?P<pk>\d+)/quantity/(?P<quantity>\d+)/$', basketapp.change),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('my/admin/', include('adminapp.urls', namespace='my_admin')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    path('auth/register/', include('social_django.urls', namespace='social')),

    path('admin/', admin.site.urls, name="admin"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name="index"),
    path('products/', mainapp.products, name="products"),
    path('products/<int:page>/', mainapp.products, name="same_products_pagination"),
    re_path(r'^category/(?P<pk>\d+)/products/$', mainapp.category_products, name="category_products"),
    # path(r'category/<int:pk>/products/', mainapp.category_products, name="category_products"),
    re_path(r'^category/(?P<pk>\d+)/products/(?P<page>\d+)/$', mainapp.category_products,
            name="category_products_pagination"),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product_page, name='product_page'),
    path('contacts/', cache_page(86400)(mainapp.contacts), name="contacts"),

    re_path(r'^product/detail/(?P<pk>\d+)/async/$', mainapp.product_detail_async),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField('Название', max_length=128, unique=True)
    description = models.TextField('Описание', max_length=255, blank=True)
    is_active = models.BooleanField(default=True, db_index=True)
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)

    def __str__(self):
        return f'{self.name}'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.PROTECT, verbose_name='Категория')
    name = models.CharField('Название', max_length=128)
    short_description = models.CharField('Краткое описание', max_length=128, blank=True)
    description = models.TextField('Описание', blank=True)
    quantity = models.PositiveIntegerField('Количество', default=0)
    price = models.DecimalField('Цена', max_digits=10, decimal_places=0, default=0)
    image = models.ImageField(upload_to='products_images', blank=True)
    is_active = models.BooleanField(default=True, db_index=True)
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)
    updated_at = models.DateTimeField('Дата обновления', auto_now=True)

    @staticmethod
    def get_active_items():
        return Product.objects.select_related().filter(category__is_active=True, is_active=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

geekshop/mainapp/views.py
import random

from django.core.cache import cache
from django.views.decorators.cache import cache_page, never_cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
import json

from mainapp.models import ProductCategory, Product

from geekshop.settings import LOW_CACHE


def get_category_list():
    if LOW_CACHE:
        key = 'category_list'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if LOW_CACHE:
        key = f'productcategory_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_in_productcategory(pk):
    if LOW_CACHE:
        key = f'products_in_productcategory_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True)
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True,category__is_active=True)


def index(request):
    context = {
        'page_title': 'Interior',
    }
    return render(request, 'mainapp/index.html', context)


# @cache_page(3600)
# @never_cache
def products(request, page=1):
    # categories = ProductCategory.objects.all()
    # products_list = Product.objects.all()
    hot_product_pk = random.choice(Product.objects.filter(is_active=True).values_list('pk', flat=True))
    hot_product = get_product(hot_product_pk)
    same_products = hot_product.category.product_set.filter(is_active=True).select_related().exclude(pk=hot_product.pk)

    products_paginator = Paginator(same_products, 1)
    try:
        same_products = products_paginator.page(page)
    except PageNotAnInteger:
        same_products = products_paginator.page(1)
    except EmptyPage:
        same_products = products_paginator.page(products_paginator.num_pages)

    context = {
        'page_title': 'Products',
        'categories': get_category_list(),
        # 'products': products_list[:3],
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/product-details.html', context)


def category_products(request, pk, page=1):
    # categories = ProductCategory.objects.all()
    if pk == '0':
        category = {'pk': 0, 'name': 'Все'}
        products_list_category = get_products()
    else:
        category = get_category(pk)
        products_list_category = get_products_in_productcategory(pk)

    products_paginator = Paginator(products_list_category, 3)
    try:
        products_list_category = products_paginator.page(page)
    except PageNotAnInteger:
        products_list_category = products_paginator.page(1)
    except EmptyPage:
        products_list_category = products_paginator.page(products_paginator.num_pages)

    context = {
        'page_title': 'Products',
        'categories': get_category_list(),
        'products': products_list_category,
        'category': category,
    }
    return render(request, 'mainapp/category_products.html', context)


# @never_cache
def product_page(request, pk):
    # categories = ProductCategory.objects.all()
    product = get_product(pk)
    context = {
        'page_title': 'каталог',
        'categories': get_category_list(),
        'category': product.category,
        'product': product,
    }
    return render(request, 'mainapp/product.html', context)


# @cache_page(86400)
def contacts(request):
    with open('locations.json', 'r', encoding="utf-8") as file:
        locations = json.load(file)

    context = {
        'page_title': 'Contacts',
        'locations': locations,
    }

    return render(request, 'mainapp/contacts.html', context)


def product_detail_async(request, pk):
    if request.is_ajax():
        try:
            product = get_product(pk)
            return JsonResponse({
                'product_price': product.price,
            })
        except Exception as e:
            return JsonResponse({
                'error': str(e)
            })

geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
	<meta charset="UTF-8">
	<title>
        {% block title %}
            {{ page_title|title }}
        {% endblock %}
    </title>
    {% block css %}
<!--        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">-->
	    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
<!--        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>-->
<!--        <script src="{% static 'js/bootstrap.min.js' %}"></script>-->
    {% endblock %}
</head>
<body>
	<div class="container">
        {% block container %}
        {% endblock %}
	</div>
    {% block footer %}
        <div class="footer clearfix">
        <div class="info padding-site">
            <div class="contacts">
                <div class="contacts-header">
                    Contact Us
                </div>
                <div class="contacts-text">
                    132A Bridge Road Richmond VIC Australia.<br>
                    <br>
                    Talk to us on 1300 132<br>
                    info@interior.com
                </div>
            </div>
            <div class="useful-info">
                <div class="useful-info-header">
                    Useful Information
                </div>
                <div class="useful-lists">
                    <ul class="useful-info-list-1">
                        <li class="useful-info-list"><a href="#" class="useful-info-link">Sales terms</a></li>
                        <li class="useful-info-list"><a href="#" class="useful-info-link">Customer care</a></li>
                        <li class="useful-info-list"><a href="#" class="useful-info-link">Delivery</a></li>
                    </ul>
                    <ul class="useful-info-list-2">
                        <li class="useful-info-list"><a href="#" class="useful-info-link">Architect accounts</a></li>
                        <li class="useful-info-list"><a href="#" class="useful-info-link">Careers</a></li>
                        <li class="useful-info-list"><a href="#" class="useful-info-link">Exchanges & returns</a></li>
                    </ul>
                </div>
            </div>
            <div class="subscribe">
                <div class="subscribe-header">
                    Let’s Stay in Touch!
                </div>
                <div class="subscribe-text">
                    Suscribe to know about our latest news, products and special offers just for suscribers.
                </div>
                <input class="form-email" type="email" placeholder="your email address">
                <img class="icon-email" src="{% static 'icons/mail.png' %}" alt="mail">
            </div>
        </div>
        <div class="links-footer padding-site clearfix">
            <div class="copyright">© Copyright - INTERIOR {% now "Y" %}. All Rights Reserved.
            </div>
            <div class="social-links"><img src="{% static 'icons/social-links.png' %}" alt="social-links"></div>
            <div class="terms"><a href="#" class="terms-link">Terms & Conditions</a>&nbsp;/&nbsp;<a href="#" class="terms-link">Privacy policy & Cookies</a></div>
        </div>
    </div>
    {% endblock %}
</body>
</html>

geekshop/mainapp/templates/mainapp/category_products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_filters %}

{% block container %}
	<div class="product-header padding-site">
		{% include 'mainapp/includes/inc__main_menu.html' %}
	</div>
    {% include 'mainapp/includes/inc__categories_menu.html' %}
    <div class="paginator">
        {% if products.has_previous %}
            <a href="{% url 'main:category_products_pagination' category.pk 1 %}">
                <<
            </a>
            <a href="{% url 'main:category_products_pagination' category.pk products.previous_page_number %}">
                <
            </a>
        {% endif %}
        <span class="current">страница {{ products.number }} из {{ products.paginator.num_pages }}</span>
        {% if products.has_next %}
            <a href="{% url 'main:category_products_pagination' category.pk products.next_page_number %}">
                >
            </a>
            <a href="{% url 'main:category_products_pagination' category.pk products.paginator.num_pages %}">
                >>
            </a>
        {% endif %}
    </div>
	<div class="related-products-block clearfix padding-site">
        <div class="related-products-head clearfix">
            <div class="related-products-block-header">
                Продукты в категории {{ category.name|title }}
            </div>
            <ul class="related-product-gallery">
                {% for product in products %}
                   <li class="related-product-gallery-list">
                        <a href="{% url 'mainapp:product_page' product.pk %}" class="related-product-gallery-link">
						    <img src="{{ product.image|media_folder_products }}" alt="{{product.short_description}}">
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
	<div class="contact-header padding-site">
		{% include 'mainapp/includes/inc__main_menu.html' %}
		<div class="contacts-heading">
			Contact Us
		</div>
	</div>
	<ul class="contacts-cards">
		{% if locations %}
			{% for item in locations %}
				<li class="contacts-cards-list">
					<div class="contacts-cards-list-text"><img src="{% static 'icons/point.png' %}" alt="point">
						<div class="contact-city">{{ item.city }}</div>
						<p class="header-contact-card">Phone:</p>
						<p class="header-contact-text">{{ item.phone }}</p><br>
						<p class="header-contact-card">Email:</p>
						<p class="header-contact-text">{{ item.email }}</p><br>
						<p class="header-contact-card">Address:</p>
						<p class="header-contact-adress">{{ item.address }}</p>
					</div>
				</li>
			{% endfor %}
		{% else %}
			<p class="header-contact-text">Загрузка...</p>
		{% endif %}
	</ul>
	<div class="clr clearfix">
	</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
	<div class="slider padding-site">
		{% include 'mainapp/includes/inc__main_menu.html' %}
		<div class="slider-text">
			<p class="slider-tranding">TRENDING</p>
			<h2 class="slider-header">Fishnet Chair</h2>
			<p class="slider-content">
				Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black
			</p>
		</div>
		<div class="button">
			<a href="#" class="button-link">Order Us<span class="arrow-button"><img src="{% static 'icons/arrow.svg' %}" alt="arrow"></span></a>
		</div>
		<div class="slider-pagination">
			<a href="#" class="slider-pagination-circle"></a><a href="#" class=" slider-pagination-circle slider-pagination-circle-active"></a><a href="#" class="slider-pagination-circle"></a>
		</div>
	</div>
	<div class="featured padding-site">
		<div class="featured-header clearfix">
			<ul class="featured-tabs">
				<li class="featured-tabs-list"><a href="#" class="featured-tabs-link featured-tabs-link-active">
					Featured</a>
				</li>
				<li class="featured-tabs-list"><a href="#" class="featured-tabs-link">
					New</a>
				</li>
			</ul>
			<div class="explore-all clearfix"><a href="#" class="explore-all-link">Explore all<span class="arrow-button"><img src="{% static 'icons/arrow.svg' %}" alt="arrow"></span></a>
			</div>
		</div>
		<ul class="featured-products clearfix">
			<li class="featured-product-list"><a href="#" class="featured-product-link featured-product-link-active"><img src="{% static 'img/product-1.jpg' %}" alt="photo1"></a></li>
			<li class="featured-product-list"><a href="#" class="featured-product-link"><img src="{% static 'img/product-2.jpg' %}" alt="photo2"></a></li>
			<li class="featured-product-list"><a href="#" class="featured-product-link"><img src="{% static 'img/product-3.jpg' %}" alt="photo3"></a></li>
			<li class="featured-product-list"><a href="#" class="featured-product-link"><img src="{% static 'img/product-4.jpg' %}" alt="photo4"></a></li>
		</ul>
	</div>
	<div class="exclusive clearfix">
		<div class="exclusive-block-1">
			<div class="exclusive-text">
				<div class="exclusive-text-theme">
					exclusive
				</div>
				<div class="exclusive-text-heading">
					Fishnet Chair
				</div>
				<div class="exclusive-text-text">
					Seat and back with upholstery made of cold cure foam. Steel frame, available in matt
				</div>
				<div class="button">
					<a href="#" class="button-link">Order Us<span class="arrow-button"><img src="{% static 'icons/arrow.svg' %}" alt="arrow"></span></a>
				</div>
			</div>
		</div>
		<div class="exclusive-block-2">
			<div class="exclusive-text">
				<div class="exclusive-text-theme">
					exclusive
				</div>
				<div class="exclusive-text-heading">
					Fishnet Chair
				</div>
				<div class="exclusive-text-text">
					Seat and back with upholstery made of cold cure foam. Steel frame, available in matt
				</div>
				<div class="button">
					<a href="#" class="button-link">Order Us<span class="arrow-button"><img src="{% static 'icons/arrow.svg' %}" alt="arrow"></span></a>
				</div>
			</div>
		</div>
	</div>
	<div class="trending padding-site">
		<div class="trending-header clearfix">
			<div class="trending-header-text">
				Trending Products
			</div>
			<div class="explore-all clearfix"><a href="#" class="explore-all-link">Explore all<span class="arrow-button"><img src="{% static 'icons/arrow.svg' %}" alt="arrow"></span></a>
			</div>
		</div>
		<table class="trending-gallery">
			<tr>
				<td class="trending-gallery-photo"><img src="{% static 'img/product-11.jpg' %}" alt="product-11"></td>
				<td class="trending-gallery-photo"><img src="{% static 'img/product-21.jpg' %}" alt="product-21"></td>
				<td class="trending-gallery-photo"><img src="{% static 'img/product-31.jpg' %}" alt="product-31"></td>
			</tr>
			<tr>
				<td class="trending-gallery-photo"><img src="{% static 'img/product-41.jpg' %}" alt="product-41"></td>
				<td class="trending-gallery-photo"><img src="{% static 'img/product-5.jpg' %}" alt="product-5"></td>
				<td class="trending-gallery-photo"><img src="{% static 'img/product-6.jpg' %}" alt="product-6"></td>
			</tr>
		</table>
	</div>
	<div class="slider-center padding-site">
		<div class="slider-center-text">
			<p class="slider-center-theme">Hot deal</p>
			<h2 class="slider-center-header">Fishnet Chair</h2>
			<p class="slider-center-content">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black
			</p>
		</div>
		<div class="button">
			<a href="#" class="button-link">Order Us<span class="arrow-button"><img src="{% static 'icons/arrow.svg' %}" alt="arrow"></span></a>
		</div>
		<div class="slider-pagination">
			<a href="#" class="slider-pagination-circle"></a><a href="#" class=" slider-pagination-circle slider-pagination-circle-active"></a><a href="#" class="slider-pagination-circle"></a>
		</div>
	</div>
	<div class="gallery padding-site">
		<div class="gallery-main-photo">
			<div class="gallery-main-text">
				<p class="gallery-main-theme">exclusive</p>
				<h2 class="gallery-main-header">Fishnet Chair</h2>
				<p class="gallery-main-content">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt
				</p>
				<div class="button">
					<a href="#" class="button-link">Order Us<span class="arrow-button"><img src="{% static 'icons/arrow.svg' %}" alt="arrow"></span></a>
				</div>
			</div>
		</div>
		<table class="table-gallery">
			<tr>
				<td class="table-gallery-photo"><img src="{% static 'img/product-2-sm.jpg' %}" alt="product-2-sm"></td>
				<td class="table-gallery-photo"><img src="{% static 'img/product-3-sm.jpg' %}" alt="product-3-sm"></td>
			</tr>
			<tr>
				<td class="table-gallery-photo"><img src="{% static 'img/product-4-sm.jpg' %}" alt="product-4-sm"></td>
				<td class="table-gallery-photo"><img src="{% static 'img/product-5-sm.jpg' %}" alt="product-5-sm"></td>
			</tr>
		</table>
	</div>
	<div class="clr clearfix"></div>
	<div class="mobile-app">
		<div class="mobile-app-text">
			<p class="mobile-app-theme">mobile app</p>
			<h2 class="mobile-app-header">Find. Follow. Favorite.</h2>
			<p class="mobile-app-content">Save your favorites and share your style.
			</p>
			<div class="mobile-app-app-tore"><a href="#" class="button-link"><img src="{% static 'img/app-store.png' %}" alt="app-store.png"></a>
			</div>
			<div class="mobile-app-google-play"><a href="#" class="button-link"><img src="{% static 'img/google-play.png' %}" alt="google-play"></a>
			</div>
		</div>
	</div>
	{% if message %}
		<script>
			alert('{{ message }}');
		</script>
	{% endif %}
{% endblock %}

geekshop/mainapp/templates/mainapp/product-details.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_filters %}

{% block container %}
	<div class="product-header padding-site">
		{% include 'mainapp/includes/inc__main_menu.html' %}
	</div>
	{% include 'mainapp/includes/inc__categories_menu.html' %}
	<div class="product-info padding-site">
		<ul class="product-info-image-text clearfix">
			<li class="product-info-image-text-list main-product-info-image-text-list"><img src="{{ hot_product.image|media_folder_products }}" alt="slider1"></li>
			<li class="product-info-image-text-list product-info-text">
				<div class="product-info-text-header">
					{{ hot_product.name }}
				</div>
				<div class="product-info-text-tag">
					Hot Deal
				</div>
				<div class="product-info-text-price">
					<span class="product-info-text-price-number">{{ hot_product.price }}</span> rub.
				</div>
				<div class="product-info-text-button">
					<a href="{% url 'basket:add_product' hot_product.pk %}" class="product-info-text-button-link">Order Us<span class="product-info-text-arrow-button"><img src="{% static 'icons/arrow-white.svg' %}" alt="arrow"></span></a>
				</div>
				<div class="product-info-text-text">
					{{ hot_product.description }}
				</div>
			</li>
		</ul>
		<ul class="product-photo-slider clearfix">
			<li class="product-photo-slider-list"><img src="{{ hot_product.image|media_folder_products }}" alt="controll"></li>
			<li class="product-photo-slider-list"><img src="{{ hot_product.image|media_folder_products }}" alt="controll11"></li>
			<li class="product-photo-slider-list product-photo-slider-list-active"><img src="{{ hot_product.image|media_folder_products }}" alt="controll2"></li>
		</ul>
	</div>
	<div class="related-products clearfix padding-site">
		<div class="related-products-head clearfix">
			<div class="related-products-header">
			Related Products
			</div>
			<div class="explore-all">
				<a href="#" class="explore-all-link">Explore all<span class="arrow-button"><img src="{% static 'icons/arrow.svg' %}" alt="arrow"></span></a>
			</div>
		</div>
		<ul class="related-product-gallery">
			{% for product in same_products %}
				<li class="related-product-gallery-list">
					<a href="{% url 'mainapp:product_page' product.pk %}" class="related-product-gallery-link">
						<img src="{{ product.image|media_folder_products }}" alt="{{product.short_description}}">
					</a>
				</li>
			{% endfor %}
		</ul>
		<div class="paginator">
            {% if same_products.has_previous %}
                <a href="{% url 'main:same_products_pagination' 1 %}">
                    <<
                </a>
                <a href="{% url 'main:same_products_pagination' same_products.previous_page_number %}">
                    <
                </a>
            {% endif %}
            <span class="current">страница {{ same_products.number }} из {{ same_products.paginator.num_pages }}</span>
            {% if same_products.has_next %}
                <a href="{% url 'main:same_products_pagination' same_products.next_page_number %}">
                    >
                </a>
                <a href="{% url 'main:same_products_pagination' same_products.paginator.num_pages %}">
                    >>
                </a>
            {% endif %}
        </div>
	</div>
	<div class="clr clearfix">
	</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_filters %}

{% block container %}
    <div class="product-header padding-site">
            {% include 'mainapp/includes/inc__main_menu.html' %}
        </div>
        {% include 'mainapp/includes/inc__categories_menu.html' %}
        <div class="product-info padding-site">
            <ul class="product-info-image-text clearfix">
                <li class="product-info-image-text-list main-product-info-image-text-list"><img src="{{ product.image|media_folder_products }}" alt="slider1"></li>
                <li class="product-info-image-text-list product-info-text">
                    <div class="product-info-text-header">
                        {{ product.name }}
                    </div>
                    <div class="product-info-text-price">
                        <span class="product-info-text-price-number">{{ product.price }}</span> rub.
                    </div>
                    <div class="product-info-text-button">
                        <a href="{% url 'basket:add_product' product.pk %}" class="product-info-text-button-link">Order Us<span class="product-info-text-arrow-button"><img src="{% static 'icons/arrow-white.svg' %}" alt="arrow"></span></a>
                    </div>
                    <div class="product-info-text-text">
                        {{ hot_product.description }}
                    </div>
                </li>
            </ul>
            <ul class="product-photo-slider clearfix">
                <li class="product-photo-slider-list"><img src="{{ product.image|media_folder_products }}" alt="controll"></li>
                <li class="product-photo-slider-list"><img src="{{ product.image|media_folder_products }}" alt="controll11"></li>
                <li class="product-photo-slider-list product-photo-slider-list-active"><img src="{{ product.image|media_folder_products }}" alt="controll2"></li>
            </ul>
        </div>

{% endblock %}